### ISSUE TITLE
Output paralelo desordenado> escribir ignition_log.csv

### ISSUE THREAD

**Issue by fdobad** [fire2a/C2F-W#15]
```
Selected (Random) ignition point for Year 1, sim 1: 478
Selected (Random) ignition point for Year 1, sim 573: 
Selected (Random) ignition point for Year 
Selected (Random) ignition point for Year 1, sim 1145: 3656114301, sim 1431: 9132
Selected (Random) ignition point for Year 1, sim 287: 8882
Selected (Random) ignition point for Year 1, sim 
Selected (Random) ignition point for Year 8591: 6227, sim 1716: 14130
```
Si el output de los hilos paralelos se interrumpe sin buffereo, como en el ejemplo, no se pueden identificar los puntos de ignicion

Para identificar los puntos de ignicion se corre el regex:
```
        simulation_id, ignition_cell = np.fromiter(
            re.findall("ignition point for Year [0-9]*, sim ([0-9]+): ([0-9]+)", log_text), dtype=dtype((int32, 2))
        ).T
```
https://github.com/fire2a/fire-analytics-qgis-processing-toolbox-plugin/blob/2969c084ae0ebdcb9b0fd7801447b66cc34f9bd4/fireanalyticstoolbox/algorithm_postsimulation.py#L100

lo que es incompatible con dividir tanto los prints.
[firesim_231226_140445.zip](https://github.com/fire2a/C2F-W/files/13772843/firesim_231226_140445.zip)

**Comment by fdobad** [comment]
ideal: escribir cada cada bloque tipo:
```
Selected (Random) ignition point for Year 1, sim 954: 1639
----------------------------- Results -----------------------------
Total Available Cells: 8792 - % of the Forest: 92.1593%
Total Burnt Cells: 1 - % of the Forest: 0.0104822%
Total Non-Burnable Cells: 747 - % of the Forest: 7.83019%
Total Firebreak Cells: 0 - % of the Forest: 0%
```

alternativa: que el simulador escriba los puntos de ignicion en un archivo distinto

**Comment by fdobad** [comment]
**prioridad 1 que el simulador escriba los puntos de ignicion en un archivo distinto**

**Comment by fdobad** [comment]
- [ ] escribir celda de ignicion y num simulacion en archivo csv
@matiasuno @lucasmurray97

**Comment by matiasuno** [comment]
Se incluyó la generación de una carpeta de ignition history, tanto para puntos aleatorios como para puntos desde archivo de ignitions. 

TO DO: 
- [ ] Checkear implementación con sim-years

**Comment by fdobad** [comment]
donde esta el pull

**Comment by fdobad** [comment]
- [x] probar pinchar donde se hace el messages
@matiasuno

**Comment by fdobad** [comment]
fixed: https://github.com/fire2a/C2F-W/pull/32
