### ISSUE TITLE
podman version of c2f

### ISSUE THREAD

**Issue by fdobad** [fire2a/C2F-W#69]
- [x] .Dockerfile
- [x] tests

**Comment by fdobad** [comment]
- [x] pod folder with Dockerfile and README
- [ ] upload a ready to use image to docker registry
- [ ] does it work in windows?

**Comment by matildeRivas** [comment]
Hay que retornar los resultados también.

**Comment by fdobad** [comment]
https://github.com/fire2a/C2F-W/issues/83#issue-2738477935

Next steps
